[package]
name = "ab-io-type"
description = "Infrastructure for zero-cost zero-copy serialization/deserialization"
keywords = ["serialization", "zero-cost", "zero-copy", "metadata", "no-std"]
categories = ["data-structures", "encoding", "no-std::no-alloc", "rust-patterns"]
repository = "https://github.com/nazar-pc/abundance"
homepage = "https://github.com/nazar-pc/abundance/tree/main/crates/shared/ab-io-type"
license = "0BSD"
version = "0.3.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
    "/CHANGELOG.md",
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
ab-io-type-derive = { workspace = true }
parity-scale-codec = { workspace = true, features = ["bytes", "derive", "max-encoded-len"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
trybuild = { workspace = true }

[features]
scale-codec = [
    "dep:parity-scale-codec",
]
serde = [
    "dep:serde",
]

[lints]
workspace = true
