[package]
name = "ab-riscv-interpreter"
description = "Composable and generic RISC-V interpreter"
keywords = ["riscv", "risc-v", "interpreter", "no-std", "const"]
categories = ["compilers", "no-std::no-alloc"]
repository = "https://github.com/nazar-pc/abundance"
homepage = "https://github.com/nazar-pc/abundance/tree/main/crates/execution/ab-riscv-interpreter"
license = "0BSD"
version = "0.0.4"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/build.rs",
    "/Cargo.toml",
    "/CHANGELOG.md",
    "/README.md",
]
links = "ab-riscv-interpreter"

[package.metadata.docs.rs]
all-features = false

[dependencies]
ab-riscv-macros = { workspace = true, features = ["proc-macro"] }
ab-riscv-primitives = { workspace = true }
no-panic-const = { workspace = true, optional = true }
replace_with = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(all(target_arch = "x86_64", not(target_feature = "avx")))'.dependencies]
cpufeatures = { workspace = true }

[build-dependencies]
ab-riscv-macros = { workspace = true, features = ["build"] }

[features]
alloc = []
# TODO: no-panic coverage is limited very slightly:
#  * `BasicInterpreterState::execute` method does not have `no_panic_const::no_panic` macro applied due to being used
#    with lots of extensions, many of which are too large, but is also trivially panic-free and only calls panic-free
#    methods
# Check that code can't panic under any conditions
no-panic = [
    "dep:no-panic-const",
    "ab-riscv-primitives/no-panic",
]

[lints]
workspace = true
