//! `TrivialType` derive must reject generic types, their metadata can't be generated by the derive

use ab_io_type::trivial_type::TrivialType;

#[derive(Copy, Clone, TrivialType)]
#[repr(C)]
struct Generic<T> {
    value: T,
}

fn main() {}
