//! This module defines the RISC-V instruction set instructions

pub mod isa;
pub mod rv32;
pub mod rv64;
#[cfg(test)]
mod test_utils;
pub mod utils;
pub mod v;
pub mod zawrs;
pub mod zicond;
pub mod zicsr;
pub mod zifencei;
pub mod zkr;
pub mod zvbb;
pub mod zvbc;

use crate::instructions::isa::{IsaExtension, MAX_ISA_EXTENSIONS, MAX_ISA_STRING_LENGTH};
use crate::registers::general_purpose::Register;
use core::any::TypeId;
use core::fmt;
use core::marker::Destruct;

/// Generic instruction
pub const trait Instruction:
    fmt::Display + fmt::Debug + [const] Destruct + Copy + Send + Sync + Sized + 'static
{
    /// Types of all fully implemented extensions.
    ///
    /// Note that this constant is auto-generated by the macro and usually doesn't need to be
    /// specified explicitly (and if done, will cause conflicts at compile time).
    const IMPLEMENTED_EXTENSIONS: &'static [TypeId];

    /// Instruction alignment in bytes, also known as `IALIGN`
    const ALIGNMENT: u8;

    /// A register type used by the instruction
    type Reg: [const] Register;

    /// Try to decode a single valid instruction
    fn try_decode(instruction: u32) -> Option<Self>;

    /// Instruction size in bytes
    fn size(&self) -> u8;

    /// Checks whether this instruction implements the given extension
    #[inline(always)]
    fn implements_extension<E>() -> bool
    where
        E: Instruction<Reg = Self::Reg>,
    {
        const { implements_extension::<Self, E>() }
    }
}

/// Checks whether instruction set `I` implements the given extension `E`.
///
/// Same as [`Instruction::implements_extension()`], but doesn't require `I` to implement
/// [`Instruction`] in `const` context, which makes it usable in [`InstructionIsa`] implementations.
pub const fn implements_extension<I, E>() -> bool
where
    I: Instruction,
    E: Instruction<Reg = I::Reg>,
{
    // TODO: Simple `.contains()` doesn't work in `const fn` yet:
    //  https://github.com/rust-lang/rust/issues/92476
    let mut index = 0;
    while index < I::IMPLEMENTED_EXTENSIONS.len() {
        if I::IMPLEMENTED_EXTENSIONS[index] == TypeId::of::<E>() {
            return true;
        }
        index += 1;
    }

    false
}

/// ISA extensions of an instruction set.
///
/// `Cfg` is a configuration of the implementation that some extensions depend on, like
/// [`VectorLengths`] for vector extensions. Instruction sets that do not depend on any
/// configuration implement this trait for any `Cfg`, in which case `()` can be used.
///
/// [`VectorLengths`]: v::VectorLengths
pub trait InstructionIsa<Cfg>
where
    Self: Instruction,
{
    /// ISA extensions defined by this instruction enum itself, without inherited ones.
    ///
    /// Empty for instruction enums that are not extensions on their own, like a collection of
    /// instructions shared by multiple extensions.
    const OWN_ISA_EXTENSIONS: &'static [IsaExtension];

    /// Storage for [`Self::ISA_EXTENSIONS`], the first `len` elements of `(array, len)` are used.
    ///
    /// Note that this constant is auto-generated by the macro and usually doesn't need to be
    /// specified explicitly (and if done, will cause conflicts at compile time).
    #[doc(hidden)]
    const ISA_EXTENSIONS_STORAGE: ([IsaExtension; MAX_ISA_EXTENSIONS], usize);

    /// All ISA extensions of the instruction set in canonical order, including inherited ones.
    ///
    /// An inherited extension is a part of the instruction set unless it was ignored as a whole.
    /// Ignoring individual instructions by name (like `ecall` in an instruction set without system
    /// calls) or individual instructions missing due to their conditions (like `amocas.b` from
    /// `Zabha` without `Zacas`) do not exclude the extension.
    const ISA_EXTENSIONS: &'static [IsaExtension] = {
        let (isa_extensions, len) = &Self::ISA_EXTENSIONS_STORAGE;
        let (isa_extensions, _) = isa_extensions.split_at(*len);
        isa_extensions
    };

    /// ISA string as used in the `Tag_RISCV_arch` attribute of ELF files, for example,
    /// `rv64i2p1_m2p0_zmmul1p0`
    const ISA_STRING: &'static str = {
        let (isa_string, len): &'static ([u8; MAX_ISA_STRING_LENGTH], usize) =
            &IsaExtension::isa_string(<Self::Reg as Register>::XLEN, Self::ISA_EXTENSIONS);
        let (isa_string, _) = isa_string.split_at(*len);

        match str::from_utf8(isa_string) {
            Ok(isa_string) => isa_string,
            Err(_error) => {
                panic!("ISA string consists of ASCII extension names and digits; qed");
            }
        }
    };
}
