[package]
name = "ab-const-fn-specialization"
description = "Attribute macro for writing a const fn together with a faster non-const specialization"
repository = "https://github.com/nazar-pc/abundance"
homepage = "https://github.com/nazar-pc/abundance/tree/main/crates/shared/ab-const-fn-specialization"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2024"
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
ab-const-fn-specialization-macro = { workspace = true }

[lints]
workspace = true
