name: gh-pages

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: gh-pages-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gh-pages:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: 'false'
          submodules: 'true'

      - name: Install mdbook with extra preprocessors
        uses: taiki-e/install-action@cb33e69fad06166ca28a42b2575e4dadabf62ee8 # 2.85.8
        with:
          tool: d2@0.7.1,mdbook@0.5,mdbook-d2@0.3.8

      - name: Create target dir
        run: mkdir gh-pages

      - name: Build rustdoc
        run: |
          cargo -Zgitoxide -Zgit doc --locked --all --no-deps --lib --all-features
          cp -r target/doc gh-pages/rust-docs
        env:
          # TODO: `-Znext-solver=globally` is a requirement for `generic_const_args`, `-Zmin-recursion-limit=256` is in
          #  turn needed for some crates due to `-Znext-solver=globally`
          RUSTDOCFLAGS: -Znext-solver=globally -Zmin-recursion-limit=256 -D rustdoc::broken-intra-doc-links -D rustdoc::private_intra_doc_links -Z unstable-options --enable-index-page

      - name: Install Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 #v3.2.1
        with:
          hugo-version: 0.164.0

      - name: Build main website
        run: |
          hugo build --minify --source website/main --destination $PWD/gh-pages

      - name: Build mdBook
        run: mdbook build website/book --dest-dir $PWD/gh-pages/book

      # This is needed for a custom domain to work
      - name: CNAME
        run: |
          echo "abundance.build" > gh-pages/CNAME
        if: ${{ github.repository_owner == 'nazar-pc' }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # 4.8.0
        with:
          branch: gh-pages
          single-commit: true
          folder: gh-pages
        if: ${{ github.event_name == 'push' }}
